### ISSUE TITLE
Logo/icon for Wifi-Connect

### ISSUE THREAD

**Issue by hafizahmmed** [anitaa1990/Wifi-Connect#5]
Hello,
Good Day, i make a logo icon for your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![wifi-connect-01](https://user-images.githubusercontent.com/38810169/40585834-d2ea0af8-61da-11e8-8e7c-66cf464a8f5f.jpg)

**Comment by anitaa1990** [comment]
Hey man thanks. This is awesome. Just add and send me a pull request.

**Comment by hafizahmmed** [comment]
PLz check  #6

And source file here 

https://drive.google.com/open?id=1ctDPGgaAKFy9Fxf0ENYBA2qHIulooJ8h
